name: _
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.8.0-221.0.dev
  flutter: 3.31.0-1.0.pre.213

workspace:
  - packages/l10n_bug_app

flutter:
  uses-material-design: true
