name: l10n_bug_app

environment:
  sdk: 3.8.0-221.0.dev
  flutter: 3.31.0-1.0.pre.213

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

flutter:
  uses-material-design: true
